# Generated by Django 4.1.13 on 2024-03-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorSpace', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('bedRooms', models.IntegerField()),
                ('bathRooms', models.IntegerField()),
                ('landSize', models.IntegerField()),
                ('yearConstructed', models.IntegerField()),
            ],
        ),
    ]
