# Generated by Django 4.1.13 on 2024-03-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentID', models.IntegerField()),
                ('name', models.CharField()),
                ('commissionRate', models.IntegerField()),
                ('company', models.CharField()),
            ],
        ),
    ]
